[package]
name = "hw02"
version = "0.1.0"
authors = ["Jeff Lai <jlai@localytics.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
